version: 0.2

phases:

  pre_build:
    commands:
      - add-apt-repository ppa:longsleep/golang-backports
      - apt update
      - apt install golang-go -y

      - go get go.mongodb.org/mongo-driver/mongo
  build:
    commands:
      - go build .

artifacts:
  files:
    - saga-recommender-api
    #- env-file