version: 0.2

phases:

  pre_build:
    commands:
      - apt-get install go -y
      - go get go.mongodb.org/mongo-driver/mongo
  build:
    commands:
      - go build .

artifacts:
  files:
    - saga-recommender-api
    #- env-file