version: 0.2

phases:

  pre_build:
    commands:
      #- add-apt-repository ppa:longsleep/golang-backports
      #- apt update
      #- apt install golang-go -y 

      - go get go.mongodb.org/mongo-driver/mongo
  build:
    commands:
      - go build -o saga-recommender-api .
      - touch env
      - echo DB_NAME=$DB_NAME >> env
      - echo DB_USER=$DB_USER >> env
      - echo DB_USER_PASS=$DB_USER_PASS >> env
      - echo DB_ENDPOINT=$DB_ENDPOINT >> env
  post_build:
    commands:
      - cat env

artifacts:
  files:
    - saga-recommender-api
    - scripts/*
    - config/*
    - appspec.yml
    - env
    #- env-file